# Generated by Django 5.0.1 on 2024-02-06 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='lastPromptDone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='volapp.prompts'),
        ),
        migrations.AddField(
            model_name='users',
            name='maxStreak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
