# Generated by Django 5.0.1 on 2024-02-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volapp', '0003_alter_users_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='publicId',
        ),
        migrations.AddField(
            model_name='posts',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
