# Generated by Django 5.0.1 on 2024-02-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volapp', '0004_remove_posts_publicid_posts_flagged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='lastPromptDone',
        ),
        migrations.AddField(
            model_name='posts',
            name='answers',
            field=models.JSONField(default={'answers': []}),
        ),
        migrations.AddField(
            model_name='posts',
            name='emotions',
            field=models.JSONField(default={'emotions': []}),
        ),
        migrations.DeleteModel(
            name='Prompts',
        ),
    ]
