# Generated by Django 5.0.1 on 2024-02-24 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volapp', '0006_alter_posts_answers_alter_posts_emotions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volapp.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volapp.users')),
            ],
        ),
    ]
