# Generated by Django 5.0.1 on 2024-02-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volapp', '0007_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='total_likes',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
